In [2]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras.layers import Embedding
from tensorflow.keras import Sequential

In [2]:
tf.__version__

'1.13.1'

In [ ]:
#======================= Input

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

x_inputs = []
x_inputs.append([1,2])
x_inputs.append([3,4])
np.array(x_inputs)

array([[1, 2],
       [3, 4]])

In [23]:
raw_inputs = []
raw_labels = []

for line in open("/Users/bytedance/LearningProjects/practice_shouqianba/test_data.txt", 'r'):
    line_inputs, line_label = line.split(' ')
    line_inputs = [int(_) - 1 for _ in line_inputs.split(',')]
    line_label = int(line_label)
    print line_inputs, line_label
    
    raw_inputs.append(line_inputs)
    raw_labels.append(line_label)

[1, 0, 4, 2] 1
[0, 3, 4, 2] 1
[0, 1, 3, 2] 0
[0, 1, 2, 3] 0


In [24]:
raw_inputs = np.array(raw_inputs)
raw_labels = np.array(raw_labels)

classes = 2
raw_labels = np.eye(classes)[raw_labels]

In [25]:
print raw_inputs
print raw_labels

[[1 0 4 2]
 [0 3 4 2]
 [0 1 3 2]
 [0 1 2 3]]
[[0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]


In [13]:
fid_size = 5
embedding_dim = 4
emb = Embedding(fid_size, embedding_dim)
inputs = tf.keras.Input(shape=(None,), dtype="int64")
#                         embeddings_initializer=feat.embeddings_initializer,
#                         embeddings_regularizer=l2(l2_reg),



In [13]:
print raw_inputs.shape,raw_labels.shape

(4, 4) (4, 1)


In [ ]:
#====================== test

In [29]:

with tf.Session() as sess:
    inputs = tf.keras.Input(shape=(4, ), dtype="int64")
    labels = tf.keras.Input(shape=(2, ), dtype="float32")
    
    emb = Embedding(5, 4)(inputs)
    concat_emb = tf.keras.layers.Flatten()(emb)
    y = concat_emb
    # y = tf.keras.layers.Dense(10, activation='relu')(concat_emb)
    prediction = tf.keras.layers.Dense(2, activation='softmax')(y)

    print prediction.shape
    print labels.shape
    
    loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=prediction, labels=labels))
    train_optim = tf.train.AdamOptimizer().minimize(loss)
    
    init = tf.global_variables_initializer()
    sess.run(init)

    for _ in range(10):
        sess.run(train_optim, feed_dict={inputs: raw_inputs, labels: raw_labels})
    
    print sess.run(loss, feed_dict={inputs: raw_inputs, labels: raw_labels})
    print sess.run(prediction, feed_dict={inputs: raw_inputs})
    print sess.run(concat_emb, feed_dict={inputs: raw_inputs})

(?, 2)
(?, 2)
0.713549
[[0.46424958 0.53575045]
 [0.4880799  0.5119201 ]
 [0.53630865 0.46369132]
 [0.5008878  0.4991122 ]]
[[-0.01590754 -0.03822625  0.0103915  -0.00088073 -0.04013641 -0.02407075
  -0.05124259 -0.02752182 -0.02439897  0.04493895  0.05284575 -0.05527276
  -0.02013768 -0.02245836 -0.03153827 -0.02312363]
 [-0.04013641 -0.02407075 -0.05124259 -0.02752182  0.0305381  -0.02574635
  -0.05172745  0.03480512 -0.02439897  0.04493895  0.05284575 -0.05527276
  -0.02013768 -0.02245836 -0.03153827 -0.02312363]
 [-0.04013641 -0.02407075 -0.05124259 -0.02752182 -0.01590754 -0.03822625
   0.0103915  -0.00088073  0.0305381  -0.02574635 -0.05172745  0.03480512
  -0.02013768 -0.02245836 -0.03153827 -0.02312363]
 [-0.04013641 -0.02407075 -0.05124259 -0.02752182 -0.01590754 -0.03822625
   0.0103915  -0.00088073 -0.02013768 -0.02245836 -0.03153827 -0.02312363
   0.0305381  -0.02574635 -0.05172745  0.03480512]]
